services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        VERSION: ${PHP_VERSION:-8.2}
    expose:
      - 9000
    restart: unless-stopped
    environment:
      ROLE: app
      APPENV: ${APP_ENV:-production}
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./wordpress:/var/www/html
    networks:
      - net
    depends_on:
      - db

  webserver:
    image: nginx:1.24.0-alpine
    ports:
      - 8001:80
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./docker/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./wordpress:/var/www/html
    networks:
      - net
    depends_on:
      - app
      - db

  db:
    image: mariadb:latest
    ports:
      - 3305:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_USER: "${DB_USERNAME:-secret}"
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  net:
    driver: bridge

volumes:
  db:
    driver: local
